// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Infrastructure.Data;

#nullable disable

namespace Warehouse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WmsContext))]
    [Migration("20260522144755_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "movement_type", new[] { "receive", "transfer", "ship", "write_off", "positive_adjustment", "negative_adjustment", "return" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", new[] { "created", "reserved", "picking", "picked", "packed", "shipped", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reservation_status", new[] { "active", "cancelled", "consumed", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "warehouse_locations_status", new[] { "active", "inactive", "blocked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "warehouse_locations_type", new[] { "storage", "picking", "packing", "damaged", "receiving" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "warehouse_status", new[] { "active", "inactive" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Api.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExternalOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_order_id");

                    b.Property<DateTime?>("PickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_at");

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_quantity");

                    b.Property<int>("PickedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("picked_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "OrderId", "ProductId" }, "uq_order_items_order_product")
                        .IsUnique();

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<int>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.Property<int>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex(new[] { "Barcode" }, "unique_barcode")
                        .IsUnique();

                    b.HasIndex(new[] { "Sku" }, "unique_sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_reserved");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_balance");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "WarehouseId", "LocationId", "ProductId" }, "uq_stock_balance_location_product")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId", "LocationId", "ProductId" }, "ux_stock_balances_location_product")
                        .IsUnique();

                    b.ToTable("stock_balances", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_movement_id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "ProductId", "CreatedAt" }, "ix_stock_movements_product_created_at")
                        .IsDescending(false, true);

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "ConsumedAt" }, "ix_stock_reservations_active_consumed")
                        .HasFilter("(status = 'active'::reservation_status)");

                    b.HasIndex(new[] { "ConsumedAt" }, "ix_stock_reservations_active_expired")
                        .HasFilter("(status = 'active'::reservation_status)");

                    b.HasIndex(new[] { "ConsumedAt" }, "ix_stock_reservations_consumed_at");

                    b.HasIndex(new[] { "IdempotencyKey" }, "unique_idempotency_key")
                        .IsUnique();

                    b.ToTable("stock_reservations", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouse");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.WarehouseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_location");

                    b.HasIndex(new[] { "WarehouseId", "Code" }, "uq_location_code")
                        .IsUnique();

                    b.HasIndex(new[] { "Id", "WarehouseId" }, "uq_location_in_warehouse")
                        .IsUnique();

                    b.ToTable("warehouse_locations", (string)null);
                });

            modelBuilder.Entity("Warehouse.Api.OrderItem", b =>
                {
                    b.HasOne("Warehouse.Api.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order");

                    b.HasOne("Warehouse.Api.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Warehouse.Api.StockBalance", b =>
                {
                    b.HasOne("Warehouse.Api.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Warehouse.Api.StockMovement", b =>
                {
                    b.HasOne("Warehouse.Api.WarehouseLocation", "FromLocation")
                        .WithMany("StockMovementFromLocations")
                        .HasForeignKey("FromLocationId")
                        .HasConstraintName("fk_from_location");

                    b.HasOne("Warehouse.Api.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_product");

                    b.HasOne("Warehouse.Api.WarehouseLocation", "ToLocation")
                        .WithMany("StockMovementToLocations")
                        .HasForeignKey("ToLocationId")
                        .HasConstraintName("fk_to_location");

                    b.HasOne("Warehouse.Api.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("fk_warehouse");

                    b.Navigation("FromLocation");

                    b.Navigation("Product");

                    b.Navigation("ToLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Api.StockReservation", b =>
                {
                    b.HasOne("Warehouse.Api.WarehouseLocation", "Location")
                        .WithMany("StockReservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_location");

                    b.HasOne("Warehouse.Api.OrderItem", "OrderItem")
                        .WithMany("StockReservations")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("fk_order_item");

                    b.HasOne("Warehouse.Api.Warehouse", "Warehouse")
                        .WithMany("StockReservations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse");

                    b.Navigation("Location");

                    b.Navigation("OrderItem");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Api.WarehouseLocation", b =>
                {
                    b.HasOne("Warehouse.Api.Warehouse", "Warehouse")
                        .WithMany("WarehouseLocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse.Api.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Warehouse.Api.OrderItem", b =>
                {
                    b.Navigation("StockReservations");
                });

            modelBuilder.Entity("Warehouse.Api.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("StockBalances");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Warehouse.Api.Warehouse", b =>
                {
                    b.Navigation("StockMovements");

                    b.Navigation("StockReservations");

                    b.Navigation("WarehouseLocations");
                });

            modelBuilder.Entity("Warehouse.Api.WarehouseLocation", b =>
                {
                    b.Navigation("StockMovementFromLocations");

                    b.Navigation("StockMovementToLocations");

                    b.Navigation("StockReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
